image: python:3.10

pages:
  stage: deploy
  cache:
    paths:
      - .cache/pip
  script:
    - pip install --cache-dir .cache/pip mkdocs mkdocs-material mkdocs-jupyter
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  only:
    - master
